#! /usr/bin/env bash
thisFolder="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"   #`dirname $_`

cd $thisFolder

echo "$PWD"


RefreshFile () 
{
  #compare files
  diff -q $1 $2 &> .file_diff

  #check file size of ".file_diff"
  if [ -s ".file_diff" ] ; then
    #file size is non zero, means compared files are different
    echo app git version changed, generating new version.h
    echo $1 -> $2
    rm $2
    cp $1 $2
  else
    echo file $2 not changed, not generating new version.h
    rm $1
  fi

  rm .file_diff
}

#********
#create repo 'ble_pepperoni' VERSION
#********

#output current ble_pepperoni commit hash
printf "\"%s\"" "$(git rev-parse HEAD)" > .version_temp
RefreshFile ".version_temp" "version.h"



#********
#create repo 'gj' VERSION
#********

cd gj
#output current git commit hash
printf "\"%s\"" "$(git rev-parse HEAD)" > ../.version_temp_gj
cd ..
RefreshFile ".version_temp_gj" "version_gj.h"



#********
#create repo 'ble_pepperoni' TAG
#********

#output current git tag 
printf "\"%s\"" "$(git describe --tag)" > .tag_temp

RefreshFile ".tag_temp" "tag.h"
